apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-credentials
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "microbank.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.global.postgresql.username | b64enc | quote }}
  password: {{ .Values.global.postgresql.password | b64enc | quote }}
