apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: microbank-mtls-strict
  namespace: student-research
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: microbank-api-gateway-ingress
  namespace: student-research
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  mtls:
    mode: STRICT
  portLevelMtls:
    "8080":
      mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: microbank-frontend-ingress
  namespace: student-research
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  mtls:
    mode: STRICT
  portLevelMtls:
    "3000":
      mode: PERMISSIVE
