apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: microbank-mtls-strict
  namespace: student-research
spec:
  mtls:
    mode: STRICT
  portLevelMtls:
    "8080":
      mode: PERMISSIVE
    "3000":
      mode: PERMISSIVE
