apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: microbank-tracing
  namespace: student-research
spec:
  tracing:
    - providers:
        - name: otel-collector
      randomSamplingPercentage: 100
      customTags:
        source_workload:
          environment:
            name: WORKLOAD_NAME
        source_namespace:
          environment:
            name: POD_NAMESPACE
        source_service_account:
          environment:
            name: SERVICE_ACCOUNT
        mesh_id:
          environment:
            name: ISTIO_META_MESH_ID