apiVersion: v1
kind: Service
metadata:
  name: {{ include "account-service.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "account-service.selectorLabels" . | nindent 4 }}
