apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-otel-collector
  namespace: {{ .Values.namespace }}
  labels:
    app: otel-collector
spec:
  type: ClusterIP
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      appProtocol: grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      protocol: TCP
      appProtocol: http
    - name: metrics
      port: 8888
      targetPort: metrics
      protocol: TCP
      appProtocol: http
