apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-service.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "notification-service.selectorLabels" . | nindent 4 }}
