apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana-datasources
  labels:
    app: grafana
    {{- include "monitoring.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "monitoring.fullname" . }}-prometheus:9090
        isDefault: true
        editable: true
