{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.grafanaHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "monitoring.fullname" . }}-grafana
                port:
                  number: 3000
    - host: {{ .Values.ingress.prometheusHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "monitoring.fullname" . }}-prometheus
                port:
                  number: 9090
{{- end }}
