apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitoring.fullname" . }}-prometheus
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "monitoring.fullname" . }}-prometheus
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [services, endpoints, pods]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "monitoring.fullname" . }}-prometheus
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "monitoring.fullname" . }}-prometheus
subjects:
  - kind: ServiceAccount
    name: {{ include "monitoring.fullname" . }}-prometheus
    namespace: {{ .Values.namespace }}
