apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transaction-service.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "transaction-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "transaction-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "transaction-service.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
        prometheus.io/path: "/actuator/prometheus"
        {{- if .Values.global.serviceMesh.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
    spec:
      containers:
        - name: transaction-service
          image: "{{ .Values.global.imageRegistry }}/microbank-transaction-service:{{ .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: 8083
              name: http
          env:
            - name: PORT
              value: "8083"
            - name: DB_HOST
              value: {{ printf "%s-postgres" .Release.Name | quote }}
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: {{ .Values.database | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-db-credentials
                  key: password
            - name: ACCOUNT_SERVICE_URL
              value: {{ printf "http://%s-account-service:8082" .Release.Name | quote }}
            - name: FRAUD_SERVICE_URL
              value: {{ printf "http://%s-fraud-service:8084" .Release.Name | quote }}
            - name: EXCHANGE_SERVICE_URL
              value: {{ printf "http://%s-exchange-service:8085" .Release.Name | quote }}
            - name: NOTIFICATION_SERVICE_URL
              value: {{ printf "http://%s-notification-service:8086" .Release.Name | quote }}
            - name: AUDIT_SERVICE_URL
              value: {{ printf "http://%s-audit-service:8087" .Release.Name | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
